export const USER_ACTION = {
    SIGN_UP: "SIGN_UP",
    SIGN_IN: "SIGN_IN",
    LOG_OUT: "LOG_OUT",
    GET_USERS: "GET_USERS",
    GET_USER_DATA: "GET_USER_DATA",
    ADD_USER: "ADD_USER",
    GET_USER: "GET_USER",
    VERIFY_USER: "VERIFY_USER",
    UPDATE_SELF: "UPDATE_SELF",
    SELECT_USER: "SELECT_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    DESREGISTER: "DESREGISTER",
}

export const ORG_ACTIONS = {
    GET_ORG: "GET_ORG",
    UPDATE_ORG: "UPDATE_ORG",
}

export const PROJECT_ACTIONS = {
    GET_PROJECTS: "GET_PROJECTS",
    GET_PROJECTS_ASSIGNED: "GET_PROJECTS_ASSIGNED",
    GET_PROJECT: "GET_PROJECT",
    SELECT_PROJECT: "SELECT_PROJECT",
    ADD_PROJECT: "ADD_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    DELETE_PROJECT: "DELETE_PROJECT",
}

export const MODAL_ACTION = {
    SET_USER_MODAL: "SET_USER_MODAL",
    SET_DELETE_USER_MODAL: "SET_DELETE_USER_MODAL",
    SET_DESREGISTER_MODAL: "SET_DESREGISTER_MODAL",
    SET_ORGANIZATION_MODAL: "SET_ORGANIZATION_MODAL",
    SET_PROJECT_MODAL: "SET_PROJECT_MODAL",
    CLOSE_ALL: "CLOSE_ALL"
}

export const SIDEPANEL_ACTIONS = {
    SET_SELECTED: "SET_SELECTED",
    SET_VISIBILITY: "SIDEPANEL_VISIBILITY",
    TOGGLE_VISIBILITY: "TOGGLE_VISIBILITY"
}